In [1]:
import pandas as pd

In [69]:
tally = pd.read_csv('../Resources/Cleaning2/clean_medal_tally.csv')

tally.head()

,Country_Name,Country_Code,Gold,Silver,Bronze,Total_Medals,Year,Season
0,United States,USA,11,7,2,20,1896,Summer
1,Greece,GRE,10,18,19,47,1896,Summer
2,Germany,GER,6,5,2,13,1896,Summer
3,France,FRA,5,4,2,11,1896,Summer
4,Great Britain,GBR,2,3,2,7,1896,Summer

In [70]:
tally = tally.drop(['Country_Code', 'Gold','Silver','Bronze'],axis = 1)
summer = tally.loc[tally["Season"] == 'Summer']
winter = tally.loc[tally["Season"] == 'Winter']

In [71]:
summer = summer.drop(['Season'], axis = 1)
winter = winter.drop(['Season'], axis = 1)
summer = summer.pivot_table('Total_Medals', ['Country_Name'], 'Year').fillna(0).astype(int).reset_index()
winter = winter.pivot_table('Total_Medals', ['Country_Name'], 'Year').fillna(0).astype(int).reset_index()

In [7]:
# add_year = summer.columns[1]

# for year in summer.columns[2:]:

#     summer[year] = summer[add_year] + summer[year]

#     add_year = year

In [8]:
# add_year = winter.columns[1]

# for year in winter.columns[2:]:

#     winter[year] = winter[add_year] + winter[year]

#     add_year = year

In [72]:
merged = pd.concat([summer, winter], axis = 0).fillna(0).reset_index()

merged.dtypes

Year
index             int64
Country_Name     object
1896            float64
1900            float64
1904            float64
1908            float64
1912            float64
1920            float64
1924              int32
1928              int32
1932              int32
1936              int32
1948              int32
1952              int32
1956              int32
1960              int32
1964              int32
1968              int32
1972              int32
1976              int32
1980              int32
1984              int32
1988              int32
1992              int32
1996            float64
2000            float64
2004            float64
2008            float64
2012            float64
2016            float64
2020            float64
1994            float64
1998            float64
2002            float64
2006            float64
2010            float64
2014            float64
2018            float64
2022            float64
dtype: object

In [48]:
merged['Country_Name'] = merged['Country_Name'].replace({'Soviet Union':'Russian Federation'})
merged.loc[merged["Country_Name"]=='Russian Federation']

Year,index,Country_Name,1896,1900,1904,1908,1912,1920,1924,1928,...,2016,2020,1994,1998,2002,2006,2010,2014,2018,2022
109,109,Russian Federation,0.0,0.0,0.0,3.0,5.0,0.0,0,0,...,56.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
119,119,Russian Federation,0.0,0.0,0.0,0.0,0.0,0.0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
186,33,Russian Federation,0.0,0.0,0.0,0.0,0.0,0.0,0,0,...,0.0,0.0,23.0,18.0,13.0,22.0,15.0,29.0,0.0,0.0
189,36,Russian Federation,0.0,0.0,0.0,0.0,0.0,0.0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [76]:
aggregation_functions = {'Country_Name':'first',1896:'sum',1900:'sum',1904:'sum',1908:'sum',1912:'sum',
                         1920:'sum',1924:'sum',1928:'sum',1932:'sum',1936:'sum',1948:'sum',1952:'sum',1956:'sum',
                         1960:'sum',1964:'sum',1968:'sum',1972:'sum',1976:'sum',1980:'sum',1984:'sum',1988:'sum',1992:'sum'
                         ,1994:'sum',1996:'sum',1998:'sum',2000:'sum',2002:'sum',2004:'sum',2006:'sum',2008:'sum',
                         2010:'sum',2012:'sum',2014:'sum',2016:'sum',2018:'sum',2020:'sum',2022:'sum'}
df_new = merged.groupby(merged['Country_Name']).aggregate(aggregation_functions)

In [77]:
df_new.columns

Index(['Country_Name',           1896,           1900,           1904,
                 1908,           1912,           1920,           1924,
                 1928,           1932,           1936,           1948,
                 1952,           1956,           1960,           1964,
                 1968,           1972,           1976,           1980,
                 1984,           1988,           1992,           1994,
                 1996,           1998,           2000,           2002,
                 2004,           2006,           2008,           2010,
                 2012,           2014,           2016,           2018,
                 2020,           2022],
      dtype='object', name='Year')

In [59]:
df_new =df_new[['Country_Name',1896,1900,1904,1908,1912,1920,1924,1928,1932,1936,1948,1952,1956,
                1960,1964,1968,1972,1976,1980,1984,1988,1992,1994,1996,1998,2000,2004,2002,2006,2008,2010,2012,2016,
                2014,2018,2020,2022]]

df_new.head()

Year,Country_Name,1896,1900,1904,1908,1912,1920,1924,1928,1932,...,2016,2020,1994,1998,2002,2006,2010,2014,2018,2022
Country_Name,,,,,,,,,,,,,,,,,,,,,
Afghanistan,Afghanistan,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Algeria,Algeria,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Argentina,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,6,7,4,...,4.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Armenia,Armenia,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,...,4.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Australasia,Australasia,0.0,0.0,0.0,5.0,7.0,0.0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [78]:
df_new.loc[df_new['Country_Name'] == 'United States']

Year,Country_Name,1896,1900,1904,1908,1912,1920,1924,1928,1932,...,2004,2006,2008,2010,2012,2014,2016,2018,2020,2022
Country_Name,,,,,,,,,,,,,,,,,,,,,
United States,United States,20.0,48.0,248.0,47.0,64.0,95.0,103,60,122,...,101.0,25.0,112.0,37.0,104.0,28.0,121.0,23.0,113.0,25.0

In [81]:
add_year = df_new.columns[1]

for year in df_new.columns[2:]:

    df_new[year] = df_new[add_year] + df_new[year]

    add_year = year
df_new.loc[df_new['Country_Name'] == "United States"]

Year,Country_Name,1896,1900,1904,1908,1912,1920,1924,1928,1932,...,2004,2006,2008,2010,2012,2014,2016,2018,2020,2022
Country_Name,,,,,,,,,,,,,,,,,,,,,
United States,United States,20.0,68.0,316.0,363.0,427.0,522.0,625.0,685.0,807.0,...,2391.0,2416.0,2528.0,2565.0,2669.0,2697.0,2818.0,2841.0,2954.0,2979.0

In [83]:
df_new[[1896,1900,1904,1908,1912,1920,1924,1928,1932,1936,1948,1952,
        1956,1960,1964,1968,1972,1976,1980,1984,1988,1992,1996,2000,
        2004,2008,2012,2016,2020,1994,1998,2002,2006,2010,2014,2018,2022 ]]=df_new[[1896,1900,1904,1908,1912,1920,1924,1928,1932,1936,1948,1952,
                                                                                    1956,1960,1964,1968,1972,1976,1980,1984,1988,1992,1996,2000,
                                                                                    2004,2008,2012,2016,2020,1994,1998,2002,2006,2010,2014,2018,2022 ]].astype(int)

df_new.dtypes

Year
Country_Name    object
1896             int32
1900             int32
1904             int32
1908             int32
1912             int32
1920             int32
1924             int32
1928             int32
1932             int32
1936             int32
1948             int32
1952             int32
1956             int32
1960             int32
1964             int32
1968             int32
1972             int32
1976             int32
1980             int32
1984             int32
1988             int32
1992             int32
1994             int32
1996             int32
1998             int32
2000             int32
2002             int32
2004             int32
2006             int32
2008             int32
2010             int32
2012             int32
2014             int32
2016             int32
2018             int32
2020             int32
2022             int32
dtype: object

In [84]:
df_new.to_excel('pivot_medals.xlsx', index = False)

In [68]:
df_new.loc[df_new['Country_Name'] == 'Soviet Union']

Empty DataFrame
Columns: [Country_Name, 1896, 1900, 1904, 1908, 1912, 1920, 1924, 1928, 1932, 1936, 1948, 1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988, 1992, 1996, 2000, 2004, 2008, 2012, 2016, 2020, 1994, 1998, 2002, 2006, 2010, 2014, 2018, 2022]
Index: []

[0 rows x 38 columns]

In [118]:
tally = tally.drop(['Country_Code','Season', 'Gold','Silver','Bronze'],axis = 1)
tally['Country_Name'] = tally['Country_Name'].replace({'Republic of Korea': 'South Korea'})
tally['Country_Name'] = tally['Country_Name'].replace({"Democratic People's Republic of Korea":'North Korea'})
tally['Country_Name'] = tally['Country_Name'].replace({'Soviet Union':'Russian Federation'})
tally['Country_Name'] = tally['Country_Name'].replace({'East Germany':'Germany'})
tally['Country_Name'] = tally['Country_Name'].replace({'West Germany':'Germany'})

tally

       Country_Name  Total_Medals  Year
0     United States            20  1896
1            Greece            47  1896
2           Germany            13  1896
3            France            11  1896
4     Great Britain             7  1896
...             ...           ...   ...
1774          Spain             1  2022
1775        Ukraine             1  2022
1776        Estonia             1  2022
1777         Latvia             1  2022
1778         Poland             1  2022

[1779 rows x 3 columns]

In [119]:
# Pivoting table, replacing NAs with 0, preventing float dtype by adding int, resetting index
tally = tally.pivot_table('Total_Medals', ['Country_Name'], 'Year').fillna(0).astype(int).reset_index()

tally

Year,Country_Name,1896,1900,1904,1908,1912,1920,1924,1928,1932,...,2004,2006,2008,2010,2012,2014,2016,2018,2020,2022
0,Afghanistan,0,0,0,0,0,0,0,0,0,...,0,0,1,0,1,0,0,0,0,0
1,Algeria,0,0,0,0,0,0,0,0,0,...,0,0,2,0,1,0,2,0,0,0
2,Argentina,0,0,0,0,0,0,6,7,4,...,6,0,6,0,4,0,4,0,3,0
3,Armenia,0,0,0,0,0,0,0,0,0,...,0,0,5,0,2,0,4,0,4,0
4,Australasia,0,0,0,5,7,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146,Vietnam,0,0,0,0,0,0,0,0,0,...,0,0,1,0,1,0,2,0,0,0
147,West Indies Federation,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
148,Yugoslavia,0,0,0,0,0,0,2,5,0,...,0,0,0,0,0,0,0,0,0,0
149,Zambia,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
150,Zimbabwe,0,0,0,0,0,0,0,0,0,...,3,0,4,0,0,0,0,0,0,0

In [120]:
# Looping through the columns and adding the previous column to each column
add_year = tally.columns[1]

for year in tally.columns[2:]:

    tally[year] = tally[add_year] + tally[year]

    add_year = year

In [121]:
tally.loc[tally["Country_Name"]=='Russian Federation']

Year,Country_Name,1896,1900,1904,1908,1912,1920,1924,1928,1932,...,2004,2006,2008,2010,2012,2014,2016,2018,2020,2022
108,Russian Federation,0,0,0,3,8,8,8,8,8,...,952,974,1034,1049,1115,1144,1200,1200,1200,1200

In [122]:
tally.to_excel('pivot_medals.xlsx')

In [30]:
tally3 = tally.drop(['Country_Code', 'Season'], axis = 1)
tally3 = tally3.sort_values(by = ['Year'], ascending = True)
tally3['Cumulative'] = tally3.groupby(['Country_Name'])['Total_Medals'].cumsum()
tally3['Gold_Cumulative'] = tally3.groupby(['Country_Name'])['Gold'].cumsum()
tally3['Silver_Cumulative'] = tally3.groupby(['Country_Name'])['Silver'].cumsum()
tally3['Bronze_Cumulative'] = tally3.groupby(['Country_Name'])['Bronze'].cumsum()

tally3.head()

,Country_Name,Gold,Silver,Bronze,Total_Medals,Year,Cumulative,Gold_Cumulative,Silver_Cumulative,Bronze_Cumulative
0,United States,11,7,2,20,1896,20,11,7,2
10,Mixed team,1,0,1,2,1896,2,1,0,1
8,Denmark,1,2,3,6,1896,6,1,2,3
7,Australia,2,0,0,2,1896,2,2,0,0
6,Austria,2,1,2,5,1896,5,2,1,2

In [40]:
tally3['Year'] = tally3.Year.astype('int32')
tally3['Year'] = pd.to_datetime(tally3.Year, format='%Y')
tally3.dtypes

Country_Name                 object
Gold                          int64
Silver                        int64
Bronze                        int64
Total_Medals                  int64
Year                 datetime64[ns]
Cumulative                    int64
Gold_Cumulative               int64
Silver_Cumulative             int64
Bronze_Cumulative             int64
dtype: object

In [91]:
summer_tally = tally3.loc[tally3['Season'] == 'Summer']
summer_tally['Cumulative'] = summer_tally.groupby(['Country_Name'])['Total_Medals'].cumsum()
summer_tally.head()

C:\Users\stwpf\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

    Country_Name  Gold  Silver  Bronze  Total_Medals  Year  Season  Cumulative
0  United States    11       7       2            20  1896  Summer          20
1         Greece    10      18      19            47  1896  Summer          47
2        Germany     6       5       2            13  1896  Summer          13
3         France     5       4       2            11  1896  Summer          11
4  Great Britain     2       3       2             7  1896  Summer           7

In [35]:
winter_tally = tally3.loc[tally3['Season'] == 'Winter']
winter_tally['Cumulative'] = winter_tally.groupby(['Country_Name'])['Total_Medals'].cumsum()
winter_tally.head()

In [45]:
tally3.to_csv('cumulative_medal.csv')
tally3.to_excel('cumulative_medals.xls')
summer_tally.to_csv('summer_cumulative.csv')

winter_tally.to_csv('winter_cumulative.csv')

In [63]:
tally2 = tally.drop(['Season', 'Country_Code', 'Year'], axis= 1)

tally2

                      Country_Name  Gold  Silver  Bronze  Total_Medals
0                    United States    11       7       2            20
1                           Greece    10      18      19            47
2                          Germany     6       5       2            13
3                           France     5       4       2            11
4                    Great Britain     2       3       2             7
5                          Hungary     2       1       3             6
6                          Austria     2       1       2             5
7                        Australia     2       0       0             2
8                          Denmark     1       2       3             6
9                      Switzerland     1       2       0             3
10                      Mixed team     1       0       1             2
11                          France    31      40      40           111
12                   United States    20      13      15            48
13                   Great Britain    20       9       9            38
14                         Belgium     6       7       5            18
15                     Switzerland     6       3       1            10
16                         Germany     4       3       2             9
17                           Italy     3       2       0             5
18                         Denmark     1       3       2             6
19                      Mixed team     1       2       3             6
20                     Netherlands     1       2       3             6
21                         Hungary     1       2       2             5
22                            Cuba     1       1       0             2
23                           Spain     1       0       0             1
24                         Austria     0       3       3             6
25                          Norway     0       2       3             5
26                           India     0       2       0             2
27                         Bohemia     0       1       1             2
28                       Australia     0       0       3             3
29                          Sweden     0       0       1             1
30                   United States    80      85      83           248
31                         Germany     5       4       5            14
32                          Canada     4       1       1             6
33                            Cuba     3       0       0             3
34                         Hungary     2       1       1             4
35                   Great Britain     1       1       0             2
36                          Greece     1       0       1             2
37                      Mixed team     1       0       0             1
38                   Great Britain    56      51      39           146
39                   United States    23      12      12            47
40                          Sweden     8       6      11            25
41                          France     5       5       9            19
42                         Germany     3       5       5            13
43                         Hungary     3       4       2             9
44                          Canada     3       3      10            16
45                          Norway     2       3       3             8
46                           Italy     2       2       0             4
47                         Belgium     1       5       2             8
48                     Australasia     1       2       2             5
49              Russian Federation     1       2       0             3
50                         Finland     1       1       3             5
51                    South Africa     1       1       0             2
52                          Greece     0       3       1             4
53                         Denmark     0       2       3             5
54                         Bohemia     0       0       2             2
55                     Netherlands     0       0       2             2
56                         Austria     0       0       1             1
57                   United States    26      19      19            64
58                          Sweden    23      25      17            65
59                   Great Britain    10      15      16            41
60                         Finland     9       8       9            26
61                          France     7       5       3            15
62                         Germany     6      13       7            26
63                           Italy     5       1       2             8
64                    South Africa     4       2       0             6
65                          Norway     3       2       5            10
66                          Canada     3       2       3             8
67                         Hungary     3       2       3             8
68                     Australasia     2       2       3             7
69                         Belgium     2       1       3             6
70                         Denmark     1       6       5            12
71                          Greece     1       0       1             2
72                     Switzerland     1       0       0             1
73              Russian Federation     0       2       3             5
74                         Austria     0       2       2             4
75                     Netherlands     0       0       3             3
76                   United States    41      27      27            95
77                          Sweden    19      20      25            64
78                         Belgium    16      12      14            42
79                         Finland    15      10       9            34
80                   Great Britain    14      16      13            43
81                           Italy    14       6       5            25
82                          Norway    13      10       9            32
83                          France     9      20      13            42
84                     Netherlands     4       2       5            11
85                         Denmark     3       9       1            13
86                    South Africa     3       4       3            10
87                          Canada     3       3       3             9
88                     Switzerland     2       2       7            11
89                         Estonia     1       2       0             3
90                          Brazil     1       1       1             3
91                       Australia     0       2       1             3
92                           Japan     0       2       0             2
93                           Spain     0       2       0             2
94                          Greece     0       1       0             1
95                      Luxembourg     0       1       0             1
96                  Czech Republic     0       0       2             2
97                     New Zealand     0       0       1             1
98                   United States    45      27      27            99
99                          France    14      15      12            41
100                        Finland    14      13      10            37
101                  Great Britain     9      14      12            35
102                          Italy     8       3       5            16
103                    Switzerland     7       8      10            25
104                         Norway     5       2       3            10
105                         Sweden     4      13      12            29
106                    Netherlands     4       1       6            11
107                        Belgium     3       7       3            13
108                      Australia     3       1       2             6
109                        Denmark     2       6       3            11
110                        Hungary     2       4       4            10
111                     Yugoslavia     2       0       0             2
112                 Czech Republic     1       4       5            10
113                      Argentina     1       3       2             6
114                        Estonia     1       1       4             6
115                   South Africa     1       1       1             3
116                     Luxembourg     1       1       0             2
117                         Greece     1       0       0             1
118                        Uruguay     1       0       0             1
119                        Austria     0       3       1             4
120                         Canada     0       3       1             4
121                        Ireland     0       1       1             2
122                         Poland     0       1       1             2
123                          Haiti     0       0       1             1
124                          Japan     0       0       1             1
125                         Monaco     0       0       1             1
126                    New Zealand     0       0       1             1
127                       Portugal     0       0       1             1
128                        Romania     0       0       1             1
129                  United States    22      18      16            56
130                        Germany    11       9      19            39
131                    Netherlands     8      10       5            23
132                        Finland     8       8       9            25
133                         France     7      12       6            25
134                         Sweden     7       6      12            25
135                          Italy     7       6       7            20
136                    Switzerland     7       6       4            17
137                        Hungary     5       5       0            10
138                  Great Britain     4      11       7            22
139                         Canada     4       4       7            15
140                      Argentina     3       3       1             7
141                        Denmark     3       2       4             9
142                        Austria     3       0       1             4
143                 Czech Republic     2       5       2             9
144                          Japan     2       2       1             5
145                         Poland     2       1       4             7
146                        Estonia     2       1       2             5
147                          Egypt     2       1       1             4
148                      Australia     1       2       1             4
149                         Norway     1       2       1             4
150                     Yugoslavia     1       1       3             5
151                   South Africa     1       0       2             3
152                          India     1       0       0             1
153                        Ireland     1       0       0             1
154                     Luxembourg     1       0       0             1
155                    New Zealand     1       0       0             1
156                          Spain     1       0       0             1
157                        Uruguay     1       0       0             1
158                        Belgium     0       1       2             3
159                          Chile     0       1       0             1
160                          Haiti     0       1       0             1
161                    Philippines     0       0       1             1
162                       Portugal     0       0       1             1
163                  United States    44      36      30           110
164                          Italy    12      12      12            36
165                         France    11       5       4            20
166                         Sweden    10       5       9            24
167                          Japan     7       7       4            18
168                        Hungary     6       5       5            16
169                        Germany     5      12       7            24
170                        Finland     5       8      12            25
171                  Great Britain     5       7       5            17
172                         Poland     3       2       4             9
173                      Australia     3       1       1             5
174                      Argentina     3       1       0             4
175                         Canada     2       5       9            16
176                    Netherlands     2       5       1             8
177                   South Africa     2       0       3             5
178                        Ireland     2       0       0             2
179                 Czech Republic     1       3       2             6
180                        Austria     1       1       3             5
181                          India     1       0       0             1
182                        Denmark     0       5       3             8
183                         Mexico     0       2       0             2
184                         Latvia     0       1       0             1
185                    New Zealand     0       1       0             1
186                    Switzerland     0       1       0             1
187                    Philippines     0       0       3             3
188                        Belgium     0       0       1             1
189                          Spain     0       0       1             1
190                        Uruguay     0       0       1             1
191                        Germany    38      31      32           101
192                  United States    24      21      12            57
193                        Hungary    10       1       5            16
194                          Italy     9      13       5            27
195                        Finland     8       6       6            20
196                         France     7       6       6            19
197                         Sweden     6       5      10            21
198                          Japan     6       4      10            20
199                    Netherlands     6       4       7            17
200                        Austria     5       7       5            17
201                    Switzerland     4       9       5            18
202                  Great Britain     4       7       3            14
203                 Czech Republic     3       5       1             9
204                      Argentina     2       2       3             7
205                        Estonia     2       2       3             7
206                          Egypt     2       1       2             5
207                         Canada     1       3       5             9
208                         Norway     1       3       2             6
209                        Türkiye     1       0       1             2
210                          India     1       0       0             1
211                    New Zealand     1       0       0             1
212                         Poland     0       4       5             9
213                        Denmark     0       2       3             5
214                         Latvia     0       1       1             2
215                        Romania     0       1       0             1
216                   South Africa     0       1       0             1
217                     Yugoslavia     0       1       0             1
218                        Belgium     0       0       3             3
219                         Mexico     0       0       3             3
220                      Australia     0       0       1             1
221                    Philippines     0       0       1             1
222                       Portugal     0       0       1             1
223                  United States    38      27      19            84
224                         Sweden    17      11      18            46
225                         France    11       6      15            32
226                        Finland    10       8       6            24
227                        Hungary    10       5      13            28
228                          Italy     9      12      10            31
229                        Türkiye     6       4       2            12
230                 Czech Republic     6       2       3            11
231                    Switzerland     5      12       6            23
232                        Denmark     5       8       9            22
233                    Netherlands     5       2       9            16
234                  Great Britain     4      16       7            27
235                      Argentina     3       3       1             7
236                      Australia     2       6       5            13
237                        Austria     2       2       4             8
238                        Belgium     2       2       3             7
239                   South Africa     2       2       2             6
240                          Egypt     2       2       1             5
241                         Mexico     2       1       2             5
242                         Norway     1       3       3             7
243                        Jamaica     1       2       0             3
244                         Poland     1       0       1             2
245                          India     1       0       0             1
246                           Peru     1       0       0             1
247                         Canada     0       2       2             4
248                     Yugoslavia     0       2       0             2
249                       Portugal     0       1       1             2
250                        Uruguay     0       1       1             2
251                           Cuba     0       1       0             1
252                          Spain     0       1       0             1
253                      Sri Lanka     0       1       0             1
254            Trinidad and Tobago     0       1       0             1
255                         Panama     0       0       2             2
256                    South Korea     0       0       2             2
257                         Brazil     0       0       1             1
258                        Ireland     0       0       1             1
259       Islamic Republic of Iran     0       0       1             1
260                    Puerto Rico     0       0       1             1
261                  United States    40      19      17            76
262             Russian Federation    22      30      19            71
263                        Hungary    16      10      16            42
264                         Sweden    12      13      10            35
265                          Italy     8       9       4            21
266                 Czech Republic     7       3       3            13
267                         France     6       6       6            18
268                        Finland     6       3      13            22
269                      Australia     6       2       3            11
270                         Norway     3       2       0             5
271                    Switzerland     2       6       6            14
272                   South Africa     2       4       4            10
273                        Jamaica     2       3       0             5
274                        Belgium     2       2       0             4
275                        Denmark     2       1       3             6
276                        Türkiye     2       0       1             3
277                          Japan     1       6       2             9
278                  Great Britain     1       2       8            11
279                      Argentina     1       2       2             5

In [64]:
#define how to aggregate various fields
agg_functions = {'Country_Name': 'first','Gold': 'sum', 'Silver': 'sum', 'Bronze':'sum', 'Total_Medals':'sum'}

#create new DataFrame by combining rows with same id values
df_new = tally2.groupby(tally2['Country_Name']).aggregate(agg_functions)

#view new DataFrame
df_new

,Country_Name,Gold,Silver,Bronze,Total_Medals
Country_Name,,,,,
Afghanistan,Afghanistan,0,0,2,2
Algeria,Algeria,5,4,8,17
Argentina,Argentina,21,26,30,77
Armenia,Armenia,2,8,8,18
Australasia,Australasia,3,4,5,12
Australia,Australia,168,177,215,560
Austria,Austria,93,124,134,351
Azerbaijan,Azerbaijan,7,14,28,49
Bahrain,Bahrain,2,2,0,4
Barbados,Barbados,0,0,1,1
Belarus,Belarus,21,37,47,105
Belgium,Belgium,48,59,67,174
Bermuda,Bermuda,1,0,1,2
Bohemia,Bohemia,0,1,3,4
Botswana,Botswana,0,1,1,2
Brazil,Brazil,37,42,71,150
Bulgaria,Bulgaria,55,90,85,230
Burkina Faso,Burkina Faso,0,0,1,1
Burundi,Burundi,1,1,0,2
Cameroon,Cameroon,3,1,2,6
Canada,Canada,146,181,220,547
Chile,Chile,2,7,4,13
Chinese Taipei,Chinese Taipei,7,11,18,36
Colombia,Colombia,5,13,16,34
Costa Rica,Costa Rica,1,1,2,4
Croatia,Croatia,18,19,15,52
Cuba,Cuba,84,69,82,235
Cyprus,Cyprus,0,1,0,1
Czech Republic,Czech Republic,80,90,102,272
Côte d'Ivoire,Côte d'Ivoire,1,1,2,4
Denmark,Denmark,48,83,83,214
Djibouti,Djibouti,0,0,1,1
Dominican Republic,Dominican Republic,3,5,4,12
Ecuador,Ecuador,3,2,0,5
Egypt,Egypt,8,10,18,36
Eritrea,Eritrea,0,0,1,1
Estonia,Estonia,14,11,19,44
Ethiopia,Ethiopia,23,12,23,58
Fiji,Fiji,2,0,1,3
Finland,Finland,149,151,185,485
France,France,272,298,340,910
Gabon,Gabon,0,1,0,1
Georgia,Georgia,10,12,18,40
Germany,Germany,608,615,615,1838
Ghana,Ghana,0,1,4,5
Great Britain,Great Britain,303,328,327,958
Greece,Greece,36,45,41,122
Grenada,Grenada,1,1,1,3
Guatemala,Guatemala,0,1,0,1
Guyana,Guyana,0,0,1,1
Haiti,Haiti,0,1,1,2
"Hong Kong, China","Hong Kong, China",2,3,4,9
Hungary,Hungary,184,158,183,525
Iceland,Iceland,0,2,2,4
India,India,10,9,16,35
Individual Olympic Athletes,Individual Olympic Athletes,1,1,3,5
Indonesia,Indonesia,8,14,15,37
Iraq,Iraq,0,0,1,1
Ireland,Ireland,11,11,16,38
Islamic Republic of Iran,Islamic Republic of Iran,24,23,29,76
Israel,Israel,3,1,9,13
Italy,Italy,263,236,270,769
Jamaica,Jamaica,26,36,25,87
Japan,Japan,186,178,211,575
Jordan,Jordan,1,1,1,3
Kazakhstan,Kazakhstan,15,24,40,79
Kenya,Kenya,35,42,36,113
Kingdom of Saudi Arabia,Kingdom of Saudi Arabia,0,2,2,4
Kosovo,Kosovo,3,0,0,3
Kuwait,Kuwait,0,0,3,3
Kyrgyzstan,Kyrgyzstan,0,3,4,7
Latvia,Latvia,5,14,12,31
Lebanon,Lebanon,0,2,2,4
Liechtenstein,Liechtenstein,2,2,6,10
Lithuania,Lithuania,6,7,13,26
Luxembourg,Luxembourg,3,4,0,7
Malaysia,Malaysia,0,8,5,13
Mauritius,Mauritius,0,0,1,1
Mexico,Mexico,13,24,35,72
Mixed team,Mixed team,4,2,4,10
Monaco,Monaco,0,0,1,1
Mongolia,Mongolia,2,11,17,30
Montenegro,Montenegro,0,1,0,1
Morocco,Morocco,7,5,12,24
Mozambique,Mozambique,1,0,1,2
Namibia,Namibia,0,5,0,5
Netherlands,Netherlands,151,155,170,476
Netherlands Antilles,Netherlands Antilles,0,1,0,1
New Zealand,New Zealand,55,35,53,143
Niger,Niger,0,1,1,2
Nigeria,Nigeria,3,11,13,27
North Korea,North Korea,16,17,24,57
North Macedonia,North Macedonia,0,1,1,2
Norway,Norway,207,187,173,567
Pakistan,Pakistan,3,3,4,10
Panama,Panama,1,0,2,3
Paraguay,Paraguay,0,1,0,1
People's Republic of China,People's Republic of China,284,231,196,711
Peru,Peru,1,3,0,4
Philippines,Philippines,1,5,8,14
Poland,Poland,82,98,149,329
Portugal,Portugal,5,9,14,28
Puerto Rico,Puerto Rico,2,2,6,10
Qatar,Qatar,2,2,4,8
Republic of Moldova,Republic of Moldova,0,2,4,6
Romania,Romania,90,97,122,309
Russian Federation,Russian Federation,696,591,589,1876
Samoa,Samoa,0,1,0,1
San Marino,San Marino,0,1,2,3
Senegal,Senegal,0,1,0,1
Serbia,Serbia,6,7,11,24
Serbia and Montenegro,Serbia and Montenegro,2,4,3,9
Singapore,Singapore,1,2,2,5
Slovakia,Slovakia,14,18,10,42
Slovenia,Slovenia,12,17,23,52
South Africa,South Africa,27,34,30,91
South Korea,South Korea,129,121,116,366
Spain,Spain,49,73,52,174
Sri Lanka,Sri Lanka,0,2,0,2
Sudan,Sudan,0,1,0,1
Suriname,Suriname,1,0,1,2
Sweden,Sweden,211,228,241,680
Switzerland,Switzerland,118,131,128,377
Syrian Arab Republic,Syrian Arab Republic,1,1,2,4
Tajikistan,Tajikistan,1,1,2,4
Thailand,Thailand,10,8,17,35
The Bahamas,The Bahamas,8,2,6,16
Togo,Togo,0,0,1,1
Tonga,Tonga,0,1,0,1
Trinidad and Tobago,Trinidad and Tobago,3,5,11,19
Tunisia,Tunisia,5,3,7,15
Turkmenistan,Turkmenistan,0,1,0,1
Türkiye,Türkiye,41,26,36,103
Uganda,Uganda,4,4,3,11
Ukraine,Ukraine,38,38,72,148
Unified Team,Unified Team,54,44,37,135
United Arab Emirates,United Arab Emirates,1,0,1,2
United Arab Republic,United Arab Republic,0,1,1,2
United Republic of Tanzania,United Republic of Tanzania,0,2,0,2
United States,United States,1179,961,839,2979
United States Virgin Islands,United States Virgin Islands,0,1,0,1
Uruguay,Uruguay,2,2,6,10
Uzbekistan,Uzbekistan,11,6,20,37
Venezuela,Venezuela,3,7,9,19
Vietnam,Vietnam,1,3,1,5
West Indies Federation,West Indies Federation,0,0,2,2
Yugoslavia,Yugoslavia,26,32,29,87
Zambia,Zambia,0,1,1,2
Zimbabwe,Zimbabwe,3,4,1,8

In [55]:
df_new.to_csv('all_medals.csv', index = False)

In [8]:
games = pd.read_csv('../Resources/Cleaning2/clean_results.csv')

games

,Result_ID,Event_Title,Sport,Result_Location,Result_Detail,Start_Date,End_Date,Time,Year,Season
0,9270,"7 metres, 1907 Rating, Open",Sailing,Oostende,na,1920-07-07,1920-07-09,na,1920,Summer
1,29722,"Featherweight (≤60 kilograms), Men",Weightlifting,"Dvorets sporta Izmaylovo, Moskva",na,1980-07-22,NaN,14:00-19:00,1980,Summer
2,54126,"Platform, Men",Diving,"Wembley Arena, Wembley, London",na,1948-08-04,1948-08-05,na,1948,Summer
3,4684,"100 metres Backstroke, Men",Swimming,"Zwemstadion van Antwerpen, Antwerpen",na,1920-08-22,1920-08-23,na,1920,Summer
4,1465,"Slalom, Men",Alpine Skiing,"Park City Mountain Resort, Park City, Utah (Kn...",Jesse Hunt,2002-02-23,NaN,na,2002,Winter
...,...,...,...,...,...,...,...,...,...,...
7324,6049,"400 metres Freestyle, Women",Swimming,"Alberca Olímpica Francisco Márquez, Ciudad de ...",na,1968-10-19,1968-10-20,na,1968,Summer
7325,84835,"Sabre, Team, Men",Fencing,"Sportforum, Turnhalle, Reichssportfeld, Berlin...",na,1936-08-12,1936-08-13,na,1936,Summer
7326,356742,"Sprint, Men",Cycling Track,"Velódromo Olímpico do Rio, Parque Olímpico da ...",na,2016-08-12,2016-08-14,na,2016,Summer
7327,8424,"100 metres Breaststroke, Men",Swimming,"Sydney International Aquatic Centre, Olympic P...",na,2000-09-16,2000-09-17,na,2000,Summer
7328,18000430,"Shortboard, Women",Surfing,"Tsurigasaki Surfing Beach, Torami, Chiba",na,2021-07-25,2021-07-27,na,2020,Summer

In [9]:
games = games.drop(['Result_ID','Result_Location','Result_Detail',
                    'Start_Date','End_Date','Time'], axis=1)

games

                             Event_Title          Sport  Year  Season
0            7 metres, 1907 Rating, Open        Sailing  1920  Summer
1     Featherweight (≤60 kilograms), Men  Weightlifting  1980  Summer
2                          Platform, Men         Diving  1948  Summer
3             100 metres Backstroke, Men       Swimming  1920  Summer
4                            Slalom, Men  Alpine Skiing  2002  Winter
...                                  ...            ...   ...     ...
7324         400 metres Freestyle, Women       Swimming  1968  Summer
7325                    Sabre, Team, Men        Fencing  1936  Summer
7326                         Sprint, Men  Cycling Track  2016  Summer
7327        100 metres Breaststroke, Men       Swimming  2000  Summer
7328                   Shortboard, Women        Surfing  2020  Summer

[7329 rows x 4 columns]

In [10]:
summer_games = games.loc[(games['Season'] == 'Summer')]

summer_games

                             Event_Title          Sport  Year  Season
0            7 metres, 1907 Rating, Open        Sailing  1920  Summer
1     Featherweight (≤60 kilograms), Men  Weightlifting  1980  Summer
2                          Platform, Men         Diving  1948  Summer
3             100 metres Backstroke, Men       Swimming  1920  Summer
5                          Platform, Men         Diving  1992  Summer
...                                  ...            ...   ...     ...
7324         400 metres Freestyle, Women       Swimming  1968  Summer
7325                    Sabre, Team, Men        Fencing  1936  Summer
7326                         Sprint, Men  Cycling Track  2016  Summer
7327        100 metres Breaststroke, Men       Swimming  2000  Summer
7328                   Shortboard, Women        Surfing  2020  Summer

[6088 rows x 4 columns]

In [11]:

year1 = summer_games.loc[(summer_games['Year']== 1904)]
year2 = summer_games.loc[(summer_games['Year']==1900)]

pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', 400)


year1

,Event_Title,Sport,Year,Season
25,"50 yards - Olympic Championships of the Public Schools Athletic League, Elementary School Events, Boys",Athletics,1904,Summer
29,"Tug-Of-War, Men",Tug-Of-War,1904,Summer
42,"Discus Throw, Handicap - Western AAU Handicap Meeting, Men",Athletics,1904,Summer
51,"120 yards Hurdles, Handicap - Olympic Open Handicap Meeting, Men",Athletics,1904,Summer
52,"100 yards - Olympic Elementary School Championship (St. Louis), Boys Under 13 Years, Boys",Athletics,1904,Summer
61,"56-pound Weight Throw, Handicap, Men",Athletics,1904,Summer
68,"Long Jump - YMCA Championship, Men",Athletics,1904,Summer
121,"Eights, Intermediate, Men",Rowing,1904,Summer
124,"Hammer Throw, Handicap - Olympic Open Handicap Meeting, Men",Athletics,1904,Summer
188,"High Jump - Interscholastic Championships, Boys",Athletics,1904,Summer
234,"Hammer Throw, Handicap - YMCA Handicap Meet, Men",Athletics,1904,Summer
267,"1 mile - Olympic Championships of the Public Schools Athletic League, High School Events, Boys",Athletics,1904,Summer
315,"400 metres, Men",Athletics,1904,Summer
348,"880 yards - YMCA Championship, Men",Athletics,1904,Summer
378,"220 yards Hurdles - Olympic Interscholastic Handicap Meet, Boys",Athletics,1904,Summer
388,"100 yards - Interscholastic Championships, Boys",Athletics,1904,Summer
389,"Middleweight (≤158 pounds), Men",Boxing,1904,Summer
428,"120 yards Hurdles - YMCA Championship, Men",Athletics,1904,Summer
461,"Discus Throw - AAU Junior Championship, Boys",Athletics,1904,Summer
468,"Team All-Around, Apparatus Work and Field Sports, Men",Artistic Gymnastics,1904,Summer
470,"Long Jump - Olympic Interscholastic Handicap Meet, Boys",Athletics,1904,Summer
505,"High Jump - AAU Championship, Men",Athletics,1904,Summer
539,"Coxless Pairs, Intermediate, Men",Rowing,1904,Summer
568,"Discus Throw - Olympic Collegiate Championship, Men",Athletics,1904,Summer
587,"220 yards Hurdles, Handicap - AAU Handicap Meet, Men",Athletics,1904,Summer
674,"1 mile, Novice, Men",Cycling Track,1904,Summer
686,"Team Round, Women",Archery,1904,Summer
688,"Long Jump - Olympic Championships of the Public Schools Athletic League, Elementary School Events, Boys",Athletics,1904,Summer
692,"2 miles, Men",Cycling Track,1904,Summer
696,"Hammer Throw - Olympic Irish Sports, Men",Athletics,1904,Summer
703,"200 metres Hurdles, Men",Athletics,1904,Summer
760,"880 yards, Handicap - YMCA Handicap Meet, Men",Athletics,1904,Summer
772,"1 mile, Handicap, Men",Cycling Track,1904,Summer
798,"220 yards - Olympic Interscholastic Handicap Meet, Boys",Athletics,1904,Summer
811,"220 yards - Olympic Irish Sports, Men",Athletics,1904,Summer
854,"120 yards Hurdles - AAU Junior Championship, Boys",Athletics,1904,Summer
878,"56-pound Weight Throw - Anthropological Days (Cocopah), Men",Athletics,1904,Summer
884,"100 metres, Men",Athletics,1904,Summer
895,"Shot Put, Men",Athletics,1904,Summer
902,"Long Jump, Men",Athletics,1904,Summer
912,"Discus Throw - AAU Championship, Men",Athletics,1904,Summer
916,"880 yards, Handicap, Men",Swimming,1904,Summer
919,"Singles, Men",Tennis,1904,Summer
925,"2 miles, Handicap, Professionals, Men",Cycling Track,1904,Summer
941,"Individual - Qualifying for Consolation Flights, Men",Golf,1904,Summer
944,"880 yards, Handicap - Western AAU Handicap Meeting, Men",Athletics,1904,Summer
984,"Double Sculls, Intermediate, Men",Rowing,1904,Summer
992,"2 miles, Handicap - YMCA Handicap Meet, Men",Athletics,1904,Summer
1002,"½ mile, Handicap, Men",Cycling Track,1904,Summer
1020,"440 yards, Handicap - YMCA Handicap Meet, Men",Athletics,1904,Summer
1027,"5 miles - AAU Championship, Men",Athletics,1904,Summer
1077,"50 yards Freestyle, Men",Swimming,1904,Summer
1111,"880 yards - AAU Championship, Men",Athletics,1904,Summer
1116,"Hammer Throw - AAU Championship, Men",Athletics,1904,Summer
1117,"High Jump, Handicap, Men",Athletics,1904,Summer
1128,"220 yards Hurdles - YMCA Championship, Men",Athletics,1904,Summer
1135,"220 yards Hurdles, Handicap - YMCA Handicap Meet, Men",Athletics,1904,Summer
1146,"440 yards - Anthropological Days (Native Americans), Men",Athletics,1904,Summer
1147,"Individual - International President's Match, Men",Golf,1904,Summer
1180,"Épée, Individual, Men",Fencing,1904,Summer
1239,"High Jump - Olympic Irish Sports, Men",Athletics,1904,Summer
1244,"Doubles - World's Fair, Men",Tennis,1904,Summer
1285,"¼ mile, Men",Cycling Track,1904,Summer
1297,"100 yards - Western AAU Championship, Men",Athletics,1904,Summer
1309,"880 yards - Olympic Athletic Meet for Schools in Louisiana Purchase Exposition Territory, Boys",Athletics,1904,Summer
1320,"Shot Put, Handicap - Olympic Open Handicap Meeting, Men",Athletics,1904,Summer
1325,"Individual - Third Flight Consolation Championship, Men",Golf,1904,Summer
1340,"High Jump, Handicap - Western AAU Handicap Meeting, Men",Athletics,1904,Summer
1362,"56-pound Weight Throw - Olympic Irish Sports, Men",Athletics,1904,Summer
1387,"Discus Throw - YMCA Championship, Men",Athletics,1904,Summer
1399,"Double Columbia Round, Women",Archery,1904,Summer
1419,"Standing Long Jump, Men",Athletics,1904,Summer
1427,"Shot Put - AAU Junior Championship, Boys",Athletics,1904,Summer
1441,"220 yards Hurdles - Olympic Athletic Meet for Schools in Louisiana Purchase Exposition Territory, Boys",Athletics,1904,Summer
1459,"High Jump - Olympic Collegiate Championship, Men",Athletics,1904,Summer
1474,"440 yards, Handicap - Olympic Open Handicap Meeting, Men",Athletics,1904,Summer
1493,"Shot Put - Olympic Irish Sports, Men",Athletics,1904,Summer
1519,"1 mile, Handicap, Professionals, Men",Cycling Track,1904,Summer
1547,"Heavyweight (>158 pounds), Men",Boxing,1904,Summer
1558,"Shot Put - Anthropological Days (Pueblo), Men",Athletics,1904,Summer
1562,"Hammer Throw, Handicap - AAU Handicap Meet, Men",Athletics,1904,Summer
1574,"1 mile, Motorcycle - Exhibition #1, Men",Cycling Track,1904,Summer
1586,"220 yards Freestyle, Men",Swimming,1904,Summer
1618,"220 yards Hurdles - Olympic Collegiate Championship, Men",Athletics,1904,Summer
1627,"120 yards Hurdles - Olympic Interscholastic Handicap Meet, Boys",Athletics,1904,Summer
1699,"880 yards - Olympic Interscholastic Handicap Meet, Boys",Athletics,1904,Summer
1710,"440 yards - Special Athletic Events, Men",Athletics,1904,Summer
1721,"4 x 50 yards Freestyle Relay, Men",Swimming,1904,Summer
1755,"Plunge For Distance, Men",Swimming,1904,Summer
1789,"220 yards Hurdles - AAU Junior Championship, Boys",Athletics,1904,Summer
1817,"Pole Vault - Olympic Athletic Meet for Schools in Louisiana Purchase Exposition Territory, Boys",Athletics,1904,Summer
1819,"120 yards Hurdles, Handicap - AAU Handicap Meet, Men",Athletics,1904,Summer
1840,"Horizontal Bar, Men",Artistic Gymnastics,1904,Summer
1850,"High Jump - Western AAU Championship, Men",Athletics,1904,Summer
1864,"Pole Vault - YMCA Championship, Men",Athletics,1904,Summer
1876,"440 yards Breaststroke, Men",Swimming,1904,Summer
1879,"220 yards - Olympic Interscholastic Meet (State of Missouri), Boys",Athletics,1904,Summer
1908,"Parallel Bars - YMCA Individual Gymnastic Championships, Men",Artistic Gymnastics,1904,Summer
1916,"1 mile - Interscholastic Championships, Boys",Athletics,1904,Summer
1952,"Discus Throw, Handicap - AAU Handicap Meet, Men",Athletics,1904,Summer
1953,"120 yards Hurdles, Handicap, Men",Athletics,1904,Summer
1957,"1 mile - AAU Junior Championship, Boys",Athletics,1904,Summer
1960,"2 miles, Handicap - Western AAU Handicap Meeting, Men",Athletics,1904,Summer
1961,"25 miles, Men",Cycling Track,1904,Summer
1989,"220 yards - Olympic Championships of the Public Schools Athletic League, Elementary School Events, Boys",Athletics,1904,Summer
2015,"High Jump, Handicap - AAU Handicap Meet, Men",Athletics,1904,Summer
2058,"Unlimited, Two Hands, Men",Weightlifting,1904,Summer
2062,"800 metres, Men",Athletics,1904,Summer
2098,"Horse Vault - YMCA Individual Gymnastic Championships, Men",Artistic Gymnastics,1904,Summer
2105,"Single Sculls, Intermediate, Men",Rowing,1904,Summer
2136,"880 yards, Handicap - AAU Handicap Meet, Men",Athletics,1904,Summer
2137,"56-pound Weight Throw - AAU Junior Championship, Boys",Athletics,1904,Summer
2189,"4 × 440 yards Relay - Olympic Championships of the Public Schools Athletic League, High School Events, Boys",Athletics,1904,Summer
2199,"2 mile - AAU Championship, Men",Athletics,1904,Summer
2214,"120 yards Hurdles - Western AAU Championship, Men",Athletics,1904,Summer
2225,"1 mile, Professionals - Consolation #1, Men",Cycling Track,1904,Summer
2236,"Flight Shooting, Women",Archery,1904,Summer
2253,"Individual All-Around, 4 Events, Men",Artistic Gymnastics,1904,Summer
2344,"High jump - Olympic Interscholastic Meet (State of Missouri), Boys",Athletics,1904,Summer
2380,"High Jump - Anthropological Days, Men",Athletics,1904,Summer
2397,"Club Swinging, Men",Artistic Gymnastics,1904,Summer
2418,"Individual - Second Flight Consolation Championship, Men",Golf,1904,Summer
2475,"Hammer Throw, Handicap, Men",Athletics,1904,Summer
2559,"120 yards Hurdles - Olympic Athletic Meet for Schools in Louisiana Purchase Exposition Territory, Boys",Athletics,1904,Summer
2577,"Coxless Fours, Men",Rowing,1904,Summer
2603,"Long Jump, Handicap - YMCA Handicap Meet, Men",Athletics,1904,Summer
2612,"2 miles - YMCA Championship, Men",Athletics,1904,Summer
2668,"High Jump, Men",Athletics,1904,Summer
2742,"Individual, Men",Golf,1904,Summer
2761,"⅔ mile, Professionals - Grand Circuit Championship, Men",Cycling Track,1904,Summer
2763,"Singles - Louisiana Purchase Open, Men",Tennis,1904,Summer
2771,"All-Around Championship, Men",Athletics,1904,Summer
2858,"Team, Men",Golf,1904,Summer
2860,"Long Jump - Olympic Championships of the Public Schools Athletic League, High School Events, Boys",Athletics,1904,Summer
2867,"Rope Climbing, Men",Artistic Gymnastics,1904,Summer
2908,"440 yards - Olympic Championships of the Public Schools Athletic League, High School Events, Boys",Athletics,1904,Summer
2919,"Standing Triple Jump, Men",Athletics,1904,Summer
2947,"½ mile, Professionals - Grand Circuit Championship, Men",Cycling Track,1904,Summer
2963,"Marathon, Men",Athletics,1904,Summer
2989,"Foil, Individual, Men",Fencing,1904,Summer
3066,"Shot Put, Handicap - Western AAU Handicap Meeting, Men",Athletics,1904,Summer
3067,"440 yards, Handicap, Men",Swimming,1904,Summer
3075,"120 yards Hurdles - AAU Championship, Men",Athletics,1904,Summer
3083,"Basketball, Men",Basketball,1904,Summer
3086,"880 yards - Olympic Collegiate Championship, Men",Athletics,1904,Summer
3114,"1 mile, Handicap - YMCA Handicap Meet, Men",Athletics,1904,Summer
3118,"Bantamweight (≤115 pounds), Men",Boxing,1904,Summer
3143,"Discus Throw, Men",Athletics,1904,Summer
3152,"Baseball Throw - Anthropological Days (Native Americans), Men",Athletics,1904,Summer
3153,"Shot Put, Handicap - YMCA Handicap Meet, Men",Athletics,1904,Summer
3202,"Heavyweight, Freestyle (>158 pounds), Men",Wrestling,1904,Summer
3230,"High Jump - Olympic Championships of the Public Schools Athletic League, High School Events, Boys",Athletics,1904,Summer
3257,"½ mile, Men",Cycling Track,1904,Summer
3281,"Double Sculls, Men",Rowing,1904,Summer
3322,"220 yards - Olympic Collegiate Championship, Men",Athletics,1904,Summer
3345,"100 yards - Olympic Championships of the Public Schools Athletic League, Elementary School Events, Boys",Athletics,1904,Summer
3349,"56-pound Weight Throw - Anthropological Days (Native Americans), Men",Athletics,1904,Summer
3361,"60 metres, Men",Athletics,1904,Summer
3381,"220 yards - Interscholastic Championships, Boys",Athletics,1904,Summer
3396,"100 yards - AAU Junior Championship, Boys",Athletics,1904,Summer
3410,"1 mile - Olympic Interscholastic Handicap Meet, Boys",Athletics,1904,Summer
3415,"Hammer Throw - YMCA Championship, Men",Athletics,1904,Summer
3441,"Long Jump, Handicap - AAU Handicap Meet, Men",Athletics,1904,Summer
3484,"60 yards, Handicap, Men",Athletics,1904,Summer
3489,"Individual All-Around - YMCA Individual Gymnastic Championships, Men",Artistic Gymnastics,1904,Summer
3500,"4 miles, Team, Men",Athletics,1904,Summer
3502,"1,500 metres, Men",Athletics,1904,Summer
3517,"880 yards - Interscholastic Championships, Boys",Athletics,1904,Summer
3523,"⅓ mile, Men",Cycling Track,1904,Summer
3532,"880 yards - Olympic Championships of the Public Schools Athletic League, High School Events, Boys",Athletics,1904,Summer
3542,"Horse Vault, Men",Artistic Gymnastics,1904,Summer
3586,"56-pound Weight Throw, Handicap - Western AAU Handicap Meeting, Men",Athletics,1904,Summer
3601,"Hammer Throw - AAU Junior Championship, Boys",Athletics,1904,Summer
3609,"220 yards Hurdles, Handicap, Men",Athletics,1904,Summer
3613,"Coxless Fours, Intermediate, Men",Rowing,1904,Summer
3647,"1 mile - Olympic Interscholastic Meet (State of Missouri), Boys",Athletics,1904,Summer
3681,"1 mile - Olympic Collegiate Championship, Men",Athletics,1904,Summer
3702,"440 yards Freestyle, Men",Swimming,1904,Summer
3703,"Shot Put - Olympic Elementary School Championship (St. Louis), Boys",Athletics,1904,Summer
3705,"100 yards - Olympic Athletic Meet for Schools in Louisiana Purchase Exposition Territory, Boys",Athletics,1904,Summer
3733,"100 yards - Olympic Interscholastic Meet (State of Missouri), Boys",Athletics,1904,Summer
3762,"120 yards Hurdles - Anthropological Days (Native Americans), Men",Athletics,1904,Summer
3785,"56-pound Weight Throw - Western AAU Championship, Men",Athletics,1904,Summer
3787,"Long Jump - Olympic Athletic Meet for Schools in Louisiana Purchase Exposition Territory, Boys",Athletics,1904,Summer
3818,"Discus Throw, Handicap - Olympic Open Handicap Meeting, Men",Athletics,1904,Summer
3880,"Pole Vault, Handicap - Olympic Open Handicap Meeting, Men",Athletics,1904,Summer
3892,"Pole Vault, Handicap - Western AAU Handicap Meeting, Men",Athletics,1904,Summer
3927,"220 yards Hurdles, Handicap - Olympic Open Handicap Meeting, Men",Athletics,1904,Summer
3938,"440 yards - Olympic Collegiate Championship, Men",Athletics,1904,Summer
3940,"Pole Vault, Handicap, Men",Athletics,1904,Summer
3966,"Shot Put, Handicap - AAU Handicap Meet, Men",Athletics,1904,Summer
3987,"120 yards Hurdles - Special Athletic Events, Men",Athletics,1904,Summer
3995,"Ball Throw for Accuracy - Anthropological Days, Men",Athletics,1904,Summer
3996,"100 yards, Handicap - YMCA Handicap Meet, Men",Athletics,1904,Summer
4008,"Hammer Throw - Olympic Interscholastic Meet (State of Missouri), Boys",Athletics,1904,Summer
4009,"120 yards Hurdles - Interscholastic Championships, Boys",Athletics,1904,Summer
4013,"Pole Vault - AAU Junior Championship, Boys",Athletics,1904,Summer
4047,"440 yards, Handicap, Men",Athletics,1904,Summer
4112,"880 yards, Handicap - Olympic Open Handicap Meeting, Men",Athletics,1904,Summer
4113,"Putting Contest, Men",Golf,1904,Summer
4119,"220 yards, Handicap - Olympic Open Handicap Meeting, Men",Athletics,1904,Summer
4156,"High Jump - Olympic Championships of the Public Schools Athletic League, Elementary School Events, Boys",Athletics,1904,Summer
4159,"2 miles, Handicap - Olympic Open Handicap Meeting, Men",Athletics,1904,Summer
4173,"Double American Round, Men",Archery,1904,Summer
4185,"Team - Nassau Match, Men",Golf,1904,Summer
4229,"Discus Throw - Olympic Interscholastic Meet (State of Missouri), Boys",Athletics,1904,Summer
4230,"120 yards Hurdles - Olympic Irish Sports, Men",Athletics,1904,Summer
4235,"1 mile, Handicap, Men",Athletics,1904,Summer
4257,"Singles - World's Fair, Men",Tennis,1904,Summer
4298,"1 mile, Handicap - Western AAU Handicap Meeting, Men",Athletics,1904,Summer
4300,"440 yards - Olympic Athletic Meet for Schools in Louisiana Purchase Exposition Territory, Boys",Athletics,1904,Summer
4337,"Shot Put - Interscholastic Championships, Boys",Athletics,1904,Summer
4346,"5 miles - AAU Junior Championship, Boys",Athletics,1904,Summer
4349,"Flyweight, Freestyle (≤115 pounds), Men",Wrestling,1904,Summer
4367,"Shot Put - Olympic Championships of the Public Schools Athletic League, High School Events, Boys",Athletics,1904,Summer
4376,"Individual All-Around, Apparatus Work and Field Sports, Men",Artistic Gymnastics,1904,Summer
4389,"Shot Put - Olympic Interscholastic Handicap Meet, Boys",Athletics,1904,Summer
4396,"Sabre, Individual, Men",Fencing,1904,Summer
4433,"5 miles, Men",Cycling Track,1904,Summer
4434,"440 yards - Olympic Interscholastic Meet (State of Missouri), Boys",Athletics,1904,Summer
4439,"440 yards - Interscholastic Championships, Boys",Athletics,1904,Summer
4448,"1 mile Freestyle, Men",Swimming,1904,Summer
4468,"Light-Flyweight, Freestyle (≤105 pounds), Men",Wrestling,1904,Summer
4478,"440 yards - YMCA Championship, Men",Athletics,1904,Summer
4504,"Long Jump, Handicap - Western AAU Handicap Meeting, Men",Athletics,1904,Summer
4526,"120 yards Hurdles - Olympic Collegiate Championship, Men",Athletics,1904,Summer
4546,"Shot Put - Olympic Interscholastic Meet (State of Missouri), Boys",Athletics,1904,Summer
4568,"880 yards - Special Athletic Events, Men",Athletics,1904,Summer
4581,"5 miles, Handicap, Men",Cycling Track,1904,Summer
4592,"Pole Vault - Western AAU Championship, Men",Athletics,1904,Summer
4634,"220 yards - Olympic Championships of the Public Schools Athletic League, High School Events, Boys",Athletics,1904,Summer
4640,"Pole Vault - Olympic Interscholastic Meet (State of Missouri), Boys",Athletics,1904,Summer
4646,"Springboard, Men",Diving,1904,Summer
4651,"1 mile, Professionals - Grand Circuit Championship, Men",Cycling Track,1904,Summer
4660,"⅓ mile, Professionals - Consolation, Men",Cycling Track,1904,Summer
4661,"440 yards - Olympic Interscholastic Handicap Meet, Boys",Athletics,1904,Summer
4662,"Long Jump, Handicap, Men",Athletics,1904,Summer
4696,"Featherweight, Freestyle (≤135 pounds), Men",Wrestling,1904,Summer
4703,"Rings, Men",Artistic Gymnastics,1904,Summer
4712,"220 yards, Handicap, Men",Swimming,1904,Summer
4729,"Hammer Throw - Western AAU Championship, Men",Athletics,1904,Summer
4731,"Singles, Men",Roque,1904,Summer
4756,"880 yards, Handicap, Men",Athletics,1904,Summer
4774,"High Jump - Olympic Interscholastic Handicap Meet, Boys",Athletics,1904,Summer
4778,"880 yards - Olympic Irish Sports, Men",Athletics,1904,Summer
4813,"Triple Jump - Olympic Irish Sports, Men",Athletics,1904,Summer
4814,"1 mile - AAU Championship, Men",Athletics,1904,Summer
4842,"Long Jump - Olympic Irish Sports, Men",Athletics,1904,Summer
4913,"½ mile, Handicap, Professionals, Men",Cycling Track,1904,Summer
4919,"Shot Put, Handicap, Men",Athletics,1904,Summer
4936,"4 × 440 yards Relay - Olympic Interscholastic Meet (State of Missouri), Boys",Athletics,1904,Summer
4938,"Lightweight (≤135 pounds), Men",Boxing,1904,Summer
4947,"Pole Vault, Handicap - YMCA Handicap Meet, Men",Athletics,1904,Summer
4956,"High Jump - YMCA Championship, Men",Athletics,1904,Summer
4998,"220 yards - Olympic Elementary School Championship (St. Louis), Boys",Athletics,1904,Summer
5011,"440 yards - Olympic Elementary School Championship (St. Louis), Boys",Athletics,1904,Summer
5018,"100 yards - Anthropological Days, Men",Athletics,1904,Summer
5032,"440 yards - AAU Championship, Men",Athletics,1904,Summer
5038,"Long Jump - AAU Championship, Men",Athletics,1904,Summer
5039,"1 mile, Men",Cycling Track,1904,Summer
5076,"High Jump - AAU Junior Championship, Boys",Athletics,1904,Summer
5099,"Singles, Boys",Tennis,1904,Summer
5103,"100 yards - Olympic Interscholastic Handicap Meet, Boys",Athletics,1904,Summer
5124,"Hammer Throw - Interscholastic Championships, Boys",Athletics,1904,Summer
5126,"100 yards - Olympic Irish Sports, Men",Athletics,1904,Summer
5135,"Long Jump - Olympic Collegiate Championship, Men",Athletics,1904,Summer
5194,"Horizontal Bar - YMCA Individual Gymnastic Championships, Men",Artistic Gymnastics,1904,Summer
5206,"Shot Put - Olympic Collegiate Championship, Men",Athletics,1904,Summer
5227,"2,590 metres Steeplechase, Men",Athletics,1904,Summer
5321,"1 mile - Special Athletic Events, Men",Athletics,1904,Summer

In [35]:
mask = year1['Event_Title'].str.contains('Boys', case=False, na=False)

year1[mask].count()

Event_Title    94
Sport          94
Year           94
Season         94
dtype: int64

In [36]:
mask2 = year1['Event_Title'].str.contains('YMCA', case=False, na=False)

year1[mask2].count()

Event_Title    33
Sport          33
Year           33
Season         33
dtype: int64

In [37]:
mask3 = year1['Event_Title'].str.contains('AAU', case=False, na=False)

year1[mask3].count()

Event_Title    74
Sport          74
Year           74
Season         74
dtype: int64

In [38]:
mask4 = year1['Event_Title'].str.contains('Anthropological', case=False, na=False)

year1[mask4].count()

Event_Title    16
Sport          16
Year           16
Season         16
dtype: int64

In [142]:
year2

                                                                                                            Event_Title                Sport  Year  Season
32                                                                      Longest distance travelled (#1), Handicap, Open           Ballooning  1900  Summer
102                                                                                      Four-In-Hand Competition, Open   Equestrian Driving  1900  Summer
162                                                                                              1-2 Ton Race One, Open              Sailing  1900  Summer
176                                                                                                     Pole Vault, Men            Athletics  1900  Summer
194                                                                Team Sprint, Professionals (Course des Nations), Men        Cycling Track  1900  Summer
285                                                                                                 Kites (large), Open           Ballooning  1900  Summer
330                                                                                         Singles, Professionals, Men               Tennis  1900  Summer
352                                                                                                    Triple Jump, Men            Athletics  1900  Summer
402                                                                                       High Jump, Professionals, Men            Athletics  1900  Summer
414                                                                                                      High Jump, Men            Athletics  1900  Summer
433                                                                              Paris-Toulouse-Paris, Voiturettes, Men    Automobile Racing  1900  Summer
454                                                                                                  25 kilometres, Men        Cycling Track  1900  Summer
473                                                                                                         Sprint, Men        Cycling Track  1900  Summer
516                                                                                                     High Jump, Open   Equestrian Jumping  1900  Summer
535                                                                                             5,000 metres, Team, Men            Athletics  1900  Summer
611                                                                                Closest landing to target (#1), Open           Ballooning  1900  Summer
651                                                                                               Foil, Individual, Men              Fencing  1900  Summer
662                                                                Crossbows, Large Arrows - 35 metres, Individual, Men              Archery  1900  Summer
691                                                                                         Jeu lyonnais, Quartets, Men               Boules  1900  Summer
697                                                                                    Ascension report, Combined, Open           Ballooning  1900  Summer
705                                                                                        Shot Put, Professionals, Men            Athletics  1900  Summer
777                                                                                                      Doubles, Mixed               Tennis  1900  Summer
791                                                                                                     200 metres, Men            Athletics  1900  Summer
827                                                                                              2-3 Ton Race Two, Open              Sailing  1900  Summer
843                                                                                 Crossbows, French Championship, Men              Archery  1900  Summer
857                                                                                                   1,500 metres, Men            Athletics  1900  Summer
903                                                                                           200 metres Freestyle, Men             Swimming  1900  Summer
921                                                                                                       Football, Men             Football  1900  Summer
968                                                                                           Standing Triple Jump, Men            Athletics  1900  Summer
1016                                                                                              Course De Primes, Men        Cycling Track  1900  Summer
1036                                                                                         200 metres Backstroke, Men             Swimming  1900  Summer
1059                                                               Festival for Societies of the Seine, Individual, Men  Artistic Gymnastics  1900  Summer
1139                                                                                                         Open, Open              Sailing  1900  Summer
1237                                                     Festival for Societies of the Seine, Artistic, Individual, Men  Artistic Gymnastics  1900  Summer
1301                                                                                  110 metres Hurdles, Handicap, Men            Athletics  1900  Summer
1330                                                                                        1,000 metres Freestyle, Men             Swimming  1900  Summer
1342                                                                                            Singles, One Ball, Open              Croquet  1900  Summer
1395                                                                                            3-10 Ton Race One, Open              Sailing  1900  Summer
1532                                                                       Free Rifle, Three Positions, 300 metres, Men             Shooting  1900  Summer
1580                                          Festival for Societies of the Seine, Olympic Competition, Individual, Men  Artistic Gymnastics  1900  Summer
1603                                                                        Longest time travelled (#1), Handicap, Open           Ballooning  1900  Summer
1608                                                                         3,000 metres, Handicap, Professionals, Men        Cycling Track  1900  Summer
1656                                                                               Closest landing to target (#2), Open           Ballooning  1900  Summer
1687                                                                                              Épée, Individual, Men              Fencing  1900  Summer
1698                                                                                  Best photograph, All events, Open           Ballooning  1900  Summer
1714                                                                                    Sprint, Professionals (#2), Men        Cycling Track  1900  Summer
1785                                                                           Best photograph, 9 September event, Open           Ballooning  1900  Summer
1831                                                                 Free Rifle, Three Positions, 300 metres, Team, Men             Shooting  1900  Summer
1853                                                                                           Underwater Swimming, Men             Swimming  1900  Summer
1951                                                                    Longest distance travelled (#2), Handicap, Open           Ballooning  1900  Summer
1956                                                                     Closest landing to target (#3), Combined, Open           Ballooning  1900  Summer
1975                                                                                                    Long Jump, Open   Equestrian Jumping  1900  Summer
1985                                                                                 100 kilometres, Professionals, Men        Cycling Track  1900  Summer
2025             26th Federal Festival, Society and Association Contests, Non-Simultaneous, National Championships, Men  Artistic Gymnastics  1900  Summer
2026                                                                                        Discus Throw, Handicap, Men            Athletics  1900  Summer
2029                                                                                     Foil, Masters, Individual, Men              Fencing  1900  Summer
2084                                                                                             Sabre, Individual, Men              Fencing  1900  Summer
2149                                                                                    Paris-Toulouse-Paris, Cars, Men    Automobile Racing  1900  Summer
2301                                                                                          Pole Vault, Handicap, Men            Athletics  1900  Summer
2338                                                         Closest landing to target (#4), Self-selected target, Open           Ballooning  1900  Summer
2353                                                                                           Long Jump, Handicap, Men            Athletics  1900  Summer
2429                                                               Longest distance travelled (#4), Second Degree, Open           Ballooning  1900  Summer
2483                                                                                  Longest time travelled (#3), Open           Ballooning  1900  Summer
2496                                                                      25 kilometres Motor-paced, Professionals, Men        Cycling Track  1900  Summer
2518                                                                             Paris-Toulouse-Paris, Motorcycles, Men    Motorcycle Sports  1900  Summer
2525                                                                                        4,000 metres Freestyle, Men             Swimming  1900  Summer
2555                                                                                           Singles, Two Balls, Open              Croquet  1900  Summer
2564                                                               Crossbows, Small Arrows - 20 metres, Individual, Men              Archery  1900  Summer
2583                                                                      Greatest height achieved (#1), Handicap, Open           Ballooning  1900  Summer
2643                                                                              Free Rifle, Standing, 300 metres, Men             Shooting  1900  Summer
2648                                                                                             2-3 Ton Race One, Open              Sailing  1900  Summer
2661                                                                                      100 miles, Professionals, Men        Cycling Track  1900  Summer
2663                                                                                     400 metres, Professionals, Men            Athletics  1900  Summer
2688                                                                                           High Jump, Handicap, Men            Athletics  1900  Summer
2694  26th Federal Festival, Society and Association Contests, Non-Simultaneous, Olympic Championships, Individual, Men  Artistic Gymnastics  1900  Summer
2706                                                                                  50 kilometres, Professionals, Men        Cycling Track  1900  Summer
2735                                                                                           Doubles, Handicap, Mixed               Tennis  1900  Summer
2767                                                                             110 metres Hurdles, Professionals, Men            Athletics  1900  Summer
2808                                                                                      Individual, Professional, Men                 Golf  1900  Summer
2835                                                                                                 Unknown Event, Men              Archery  1900  Summer
2844                                                                                  400 metres Hurdles, Handicap, Men            Athletics  1900  Summer
2850                                                                                  Free Pistol, 50 metres, Team, Men             Shooting  1900  Summer
2918                                                                                  Tandem Sprint, Professionals, Men        Cycling Track  1900  Summer
3016                                                                                                         Rugby, Men                Rugby  1900  Summer
3026                                                                                                  Individual, Women                 Golf  1900  Summer
3035                                                                                       Jeu de berges, Quartets, Men               Boules  1900  Summer
3068                                                                                            Shot Put, Handicap, Men            Athletics  1900  Summer
3078                                                                                            200 metres Hurdles, Men            Athletics  1900  Summer
3123                                                                                                          Polo, Men                 Polo  1900  Summer
3124                                                                      2,500 metres Steeplechase, Professionals, Men            Athletics  1900  Summer
3128                                                            Closest landing to target (#3), Intermediate stop, Open           Ballooning  1900  Summer
3171                                                                                                      20+ Ton, Open              Sailing  1900  Summer
3176                                                                                     Au Cordon Doré, 33 metres, Men              Archery  1900  Summer
3185                                                                                            400 metres Hurdles, Men            Athletics  1900  Summer
3192                                                                                  Singles, Handicap - Class II, Men               Tennis  1900  Summer
3283                                                                      Greatest height achieved (#2), Handicap, Open           Ballooning  1900  Summer
3316                                                                                                     60 metres, Men            Athletics  1900  Summer
3330                                                                        Épée, Masters and Amateurs, Individual, Men              Fencing  1900  Summer
3348                                                                     Crossbows, Arrows - 28 metres, Individual, Men              Archery  1900  Summer
3416                                                                                   Singles, Handicap - Class I, Men               Tennis  1900  Summer
3491                                                                                                    100 metres, Men            Athletics  1900  Summer
3495                                                                                     100 metres, Professionals, Men            Athletics  1900  Summer
3519                                                                        Longest time travelled (#2), Handicap, Open           Ballooning  1900  Summer
3531                                                                              Longest distance travelled (#3), Open           Ballooning  1900  Summer
3554                                                                                   1,500 metres, Professionals, Men            Athletics  1900  Summer
3564                                                                                               Coxed Fours (2), Men               Rowing  1900  Summer
3567                                                                                                     Long Jump, Men            Athletics  1900  Summer
3576                                                                                    Sabre, Masters, Individual, Men              Fencing  1900  Summer
3580                                                                                 Special Scratch Pole Vault #1, Men            Athletics  1900  Summer
3581                                                                                                        Eights, Men               Rowing  1900  Summer
3652                                                                                                  Discus Throw, Men            Athletics  1900  Summer
3671                                                                                   5,000 metres, Professionals, Men            Athletics  1900  Summer
3700                                                                                                   Coxed Pairs, Men               Rowing  1900  Summer
3793                                                                                     Au Cordon Doré, 50 metres, Men              Archery  1900  Summer
3862                                                                                                    Individual, Men                 Golf  1900  Summer
3869                                                                                                Kites (small), Open           Ballooning  1900  Summer
3972                                                                                    Hacks and Hunter Combined, Open  Equestrian Dressage  1900  Summer
4041                                                                                                     Singles, Women               Tennis  1900  Summer
4070                                                                                                       Singles, Men               Tennis  1900  Summer
4088                                                                                      Sur La Perche À La Herse, Men              Archery  1900  Summer
4093                                                                                            3-10 Ton Race Two, Open              Sailing  1900  Summer
4187                                                                                   Doubles, Handicap - Class I, Men               Tennis  1900  Summer
4277                                                                                  Singles, Two Balls, Handicap, Men              Croquet  1900  Summer
4344                                                                                 Grand Prix de l'aéronautique, Open           Ballooning  1900  Summer
4355                                                                                  Doubles, Handicap - Class II, Men               Tennis  1900  Summer
4398                                                                                        1,500 metres, Handicap, Men            Athletics  1900  Summer
4404                                                                                    200 metres Obstacle Course, Men             Swimming  1900  Summer
4416                                                                                         Individual All-Around, Men  Artistic Gymnastics  1900  Summer

In [110]:
winter_games = games.loc[(games['Season'] == 'Winter')]

winter_games

                        Event_Title                      Sport  Year  Season
4                       Slalom, Men              Alpine Skiing  2002  Winter
20                     Singles, Men                       Luge  1998  Winter
27     Parallel Giant Slalom, Women               Snowboarding  2010  Winter
28              1,000 metres, Women  Short Track Speed Skating  2018  Winter
37                    Slalom, Women              Alpine Skiing  2022  Winter
...                             ...                        ...   ...     ...
7284              5,000 metres, Men              Speed Skating  1948  Winter
7291  Team Sprint, Classical, Women       Cross Country Skiing  2014  Winter
7293    Large Hill, Individual, Men                Ski Jumping  2006  Winter
7306    Large Hill, Individual, Men                Ski Jumping  1928  Winter
7315   12.5 kilometres Pursuit, Men                   Biathlon  2022  Winter

[1222 rows x 4 columns]

In [117]:
#define how to aggregate various fields
agg_functions = {'Year':'first','Sport':'nunique', 'Event_Title':'nunique'}

#create new DataFrame by combining rows with same id values
df_new_game = games.groupby(games['Year']).aggregate(agg_functions)

#view new DataFrame
df_new_game

      Year  Sport  Event_Title
Year
1896  1896     10           43
1900  1900     27          188
1904  1904     20          394
1906  1906      2           13
1908  1908     26          108
1912  1912     21          106
1920  1920     30          156
1924  1924     37          150
1928  1928     33          136
1932  1932     32          149
1936  1936     40          168
1948  1948     35          168
1952  1952     35          172
1956  1956     33          168
1960  1960     30          169
1964  1964     37          214
1968  1968     35          214
1972  1972     39          223
1976  1976     36          222
1980  1980     36          228
1984  1984     40          254
1988  1988     47          302
1992  1992     50          320
1994  1994     12           55
1996  1996     36          258
1998  1998     14           62
2000  2000     39          284
2002  2002     14           68
2004  2004     39          285
2006  2006     14           74
2008  2008     42          299
2010  2010     15           78
2012  2012     39          282
2014  2014     15           86
2016  2016     41          284
2018  2018     15           89
2020  2020     49          310
2022  2022     15           97

In [113]:
#define how to aggregate various fields
agg_functions = {'Year':'first','Event_Title':'nunique'}

#create new DataFrame by combining rows with same id values
df_new_game = games.groupby(games['Year']).aggregate(agg_functions)

#view new DataFrame
df_new_game

      Year  Event_Title
Year
1896  1896           43
1900  1900          188
1904  1904          394
1906  1906           13
1908  1908          108
1912  1912          106
1920  1920          156
1924  1924          150
1928  1928          136
1932  1932          149
1936  1936          168
1948  1948          168
1952  1952          172
1956  1956          168
1960  1960          169
1964  1964          214
1968  1968          214
1972  1972          223
1976  1976          222
1980  1980          228
1984  1984          254
1988  1988          302
1992  1992          320
1994  1994           55
1996  1996          258
1998  1998           62
2000  2000          284
2002  2002           68
2004  2004          285
2006  2006           74
2008  2008          299
2010  2010           78
2012  2012          282
2014  2014           86
2016  2016          284
2018  2018           89
2020  2020          310
2022  2022           97

In [67]:
#define how to aggregate various fields
agg_functions = {'Year':'first','Sport':'count'}

#create new DataFrame by combining rows with same id values
summer_new = summer_games.groupby(summer_games['Year']).aggregate(agg_functions).reset_index()

#view new DataFrame
summer_new

      Year  Sport
Year
1896  1896     43
1900  1900    188
1904  1904    402
1908  1908    113
1912  1912    110
1920  1920    164
1924  1924    143
1928  1928    128
1932  1932    133
1936  1936    151
1948  1948    154
1952  1952    158
1956  1956    147
1960  1960    150
1964  1964    188
1968  1968    187
1972  1972    205
1976  1976    198
1980  1980    203
1984  1984    228
1988  1988    270
1992  1992    286
1996  1996    273
2000  2000    302
2004  2004    303
2008  2008    317
2012  2012    302
2016  2016    306
2020  2020    336

In [69]:
#define how to aggregate various fields
agg_functions = {'Year':'first','Sport':'count'}

#create new DataFrame by combining rows with same id values
winter_new = winter_games.groupby(winter_games['Year']).aggregate(agg_functions)

#view new DataFrame
winter_new

      Year  Sport
Year
1924  1924     17
1928  1928     16
1932  1932     24
1936  1936     26
1948  1948     23
1952  1952     23
1956  1956     24
1960  1960     27
1964  1964     38
1968  1968     36
1972  1972     35
1976  1976     37
1980  1980     38
1984  1984     43
1988  1988     68
1992  1992     65
1994  1994     61
1998  1998     68
2002  2002     76
2006  2006     82
2010  2010     86
2014  2014     98
2018  2018    102
2022  2022    109

In [92]:
df_new_game.to_csv('event_total.csv', index = False)

summer_new.to_csv('summer_event.csv', index = False)

winter_new.to_csv('winter_event.csv', index = False)